#!/bin/sh
#
# Copyright (C) 2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

# Power LEDs on the XY3528 front panel:
#   green:power (GPIO4_B1) - solid on while running
#   red:power   (GPIO4_B7) - used as a network activity indicator
ucidef_set_led_default "power" "POWER" "green:power" "1"
ucidef_set_led_netdev "net" "NET" "red:power" "eth0"

board_config_flush

exit 0
